### ISSUE TITLE
Slow emergency submit

### ISSUE THREAD

**Issue by LemonAndroid** [overthq/Auxilium#62]

**Comment by LemonAndroid** [comment]
@koredefashokun 

My plan was to pull the location every 10 seconds and get the related address once a specific geo-delta is reached (distance > 50m maybe).


You had doubts about this solution's perfomance on low-end devices and limited carrier plans.

Whats your counter-proposal?

**Comment by koredefashokun** [comment]
@LemonAndroid I still think we have to find a way to determine whether to get the address or not, by passing a boolean value to the reducer. If we can't do that, we can move the place information into its own reducer (which would look very silly, tbh).
